#define DOCTEST_CONFIG_MAIN
#define DOCTEST_CONFIG_IMPLEMENT
#include "doctest.h"
#include "stress.inl"
#include "stress.inl"
#include "stress.inl"
#include "stress.inl"
#include "stress.inl"
#include "stress.inl"
#include "stress.inl"
#include "stress.inl"
#include "stress.inl"
#include "stress.inl"
