name: Clang-Tidy

on:
  push:
    branches: [dev, master]
    paths-ignore:
      - "doc/**"
      - "scripts/**"
      - "LICENSE.txt"
      - "README.md"

  pull_request:
    paths-ignore:
      - ".github/ISSUE_TEMPLATE/**"
      - "doc/**"
      - "scripts/**"
      - "LICENSE.txt"
      - "README.md"

env:
  CTEST_OUTPUT_ON_FAILURE: ON
  CTEST_PARALLEL_LEVEL: 2

concurrency:
  group: ${{ github.workflow }}|${{ github.ref_name }}|clang-tidy
  cancel-in-progress: true

jobs:
  clang-tidy:
    runs-on: ubuntu-24.04
    env:
      LLVM_VERSION: 22

    steps:
      - uses: actions/checkout@v5

      - name: Configure LLVM Upstream
        run: |
          # See apt.llvm.org
          wget -qO- http://apt.llvm.org/llvm-snapshot.gpg.key \
            | sudo tee /etc/apt/trusted.gpg.d/apt.llvm.org.asc

          sudo add-apt-repository \
            "deb http://apt.llvm.org/$(lsb_release -cs)/ llvm-toolchain-$(lsb_release -cs)-${{ env.LLVM_VERSION}} main"

      - name: Install
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build clang-tidy-${{ env.LLVM_VERSION }}

      - name: Generate
        run: |
          cmake -B build -S . -G Ninja \
            -D CMAKE_CXX_COMPILER=clang++ \
            -D CMAKE_EXPORT_COMPILE_COMMANDS=ON \
            -D CMAKE_CXX_CLANG_TIDY="clang-tidy-${{ env.LLVM_VERSION }};-warnings-as-errors=*"

      - name: Build
        run: cmake --build build
