name: Linux

on:
  push:
    branches: [dev, master]
    paths-ignore:
      - "doc/**"
      - "scripts/**"
      - "LICENSE.txt"
      - "README.md"

  pull_request:
    paths-ignore:
      - "doc/**"
      - "scripts/**"
      - "LICENSE.txt"
      - "README.md"

env:
  CTEST_OUTPUT_ON_FAILURE: ON
  CTEST_PARALLEL_LEVEL: 2
  CMAKE_GENERATOR: Ninja
  ASAN_OPTIONS: strict_string_checks=true:detect_odr_violation=2:detect_stack_use_after_return=true:check_initialization_order=true:strict_init_order=true
  TSAN_OPTIONS: force_seq_cst_atomics=1

concurrency:
  group: ${{ github.workflow }}|${{ github.ref_name }}|linux
  cancel-in-progress: true

jobs:
  clang:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - { compiler: clang, version: "3.9", os: ubuntu-24.04, container: ubuntu:18.04 }
          - { compiler: clang, version: "4.0", os: ubuntu-24.04, container: ubuntu:18.04 }
          - { compiler: clang, version: "5.0", os: ubuntu-24.04, container: ubuntu:18.04 }
          - { compiler: clang, version: "6.0", os: ubuntu-24.04, container: ubuntu:20.04 }
          - { compiler: clang, version: "7",   os: ubuntu-24.04, container: ubuntu:20.04 }
          - { compiler: clang, version: "8",   os: ubuntu-24.04, container: ubuntu:20.04 }
          - { compiler: clang, version: "9",   os: ubuntu-24.04, container: ubuntu:20.04 }
          - { compiler: clang, version: "10",  os: ubuntu-24.04, container: ubuntu:20.04 }
          - { compiler: clang, version: "11",  os: ubuntu-22.04                          }
          - { compiler: clang, version: "12",  os: ubuntu-22.04                          }
          - { compiler: clang, version: "13",  os: ubuntu-22.04                          }
          - { compiler: clang, version: "14",  os: ubuntu-24.04                          }
          - { compiler: clang, version: "15",  os: ubuntu-24.04                          }
          - { compiler: clang, version: "16",  os: ubuntu-24.04                          }
          - { compiler: clang, version: "17",  os: ubuntu-24.04                          }
          - { compiler: clang, version: "18",  os: ubuntu-24.04                          }
          - { compiler: clang, version: "19",  os: ubuntu-24.04, container: ubuntu:26.04 }
          - { compiler: clang, version: "20",  os: ubuntu-24.04, container: ubuntu:26.04 }
          - { compiler: clang, version: "21",  os: ubuntu-24.04, container: ubuntu:26.04 }

    steps:
      - uses: actions/checkout@v5

      # Ref: https://github.com/actions/checkout/issues/1590#issuecomment-2567109195
      - name: Prepare container (Linux, containerized)
        if: runner.os == 'Linux' && matrix.container != ''
        run: |
          docker pull ${{ matrix.container }}
          docker run --name build-container -d -v ${{ github.workspace }}:/workspace ${{ matrix.container }} tail -f /dev/null

          cat <<'EOF' > container-env.sh
          export CTEST_OUTPUT_ON_FAILURE="${{ env.CTEST_OUTPUT_ON_FAILURE }}"
          export CTEST_PARALLEL_LEVEL="${{ env.CTEST_PARALLEL_LEVEL }}"
          export CMAKE_GENERATOR="${{ env.CMAKE_GENERATOR }}"
          export ASAN_OPTIONS="${{ env.ASAN_OPTIONS }}"
          export TSAN_OPTIONS="${{ env.TSAN_OPTIONS }}"
          EOF

      - name: Install (Linux)
        if: runner.os == 'Linux' && matrix.container == ''
        run: |
          # Required for libc6-dbg:i386 and g++-multilib packages which are
          # needed for x86 builds.
          sudo dpkg --add-architecture i386

          sudo apt-get update
          sudo apt-get install -y cmake ninja-build valgrind libc6-dbg:i386

          # clang-17 does not automatically provide the i386 sanitizer runtimes,
          # but libclang-rt-V-dev:i386 does not always exist. This is the best intermediate option
          if [ "${{ matrix.version }}" = "17" ]; then
            sudo apt-get install -y libclang-rt-${{ matrix.version }}-dev:i386
          fi

          sudo apt-get install -y clang-${{ matrix.version }} libclang-${{ matrix.version }}-dev llvm-${{ matrix.version }}-dev g++-multilib

      - name: Install (containerized)
        if: runner.os == 'Linux' && matrix.container != ''
        env:
          CMD: |
            dpkg --add-architecture i386

            # Configure Kitware repo for newer version of CMake.
            if [ "${{ matrix.container }}" = "ubuntu:18.04" ]; then
              apt-get update && apt-get install -y wget gpg
              wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | gpg --dearmor - | tee /usr/share/keyrings/kitware-archive-keyring.gpg >/dev/null
              echo 'deb [signed-by=/usr/share/keyrings/kitware-archive-keyring.gpg] https://apt.kitware.com/ubuntu/ bionic main' | tee /etc/apt/sources.list.d/kitware.list >/dev/null
            fi

            apt-get update
            apt-get install -y cmake ninja-build valgrind libc6-dbg:i386 python3
            apt-get install -y clang-${{ matrix.version }} libclang-${{ matrix.version }}-dev llvm-${{ matrix.version }}-dev g++-multilib
        run: docker exec build-container bash -c "$CMD"

      - name: Build & Test ${{ runner.arch }}
        if: matrix.container == ''
        run: python3 .github/workflows/build_and_test.py ${{ runner.os }} ${{ runner.arch }} ${{ matrix.compiler }} ${{ matrix.version }}

      - name: Build & Test ${{ runner.arch }} (containerized)
        if: matrix.container != ''
        env:
          CMD: |
            cd /workspace
            source container-env.sh
            python3 .github/workflows/build_and_test.py ${{ runner.os }} ${{ runner.arch }} ${{ matrix.compiler }} ${{ matrix.version }}
        run: docker exec build-container bash -c "$CMD"

      - name: Build & Test X86
        if: (runner.os == 'Linux' && matrix.container == '')
        run: python3 .github/workflows/build_and_test.py ${{ runner.os }} x86 ${{ matrix.compiler }} ${{ matrix.version }}

      - name: Build & Test X86 (containerized)
        if: matrix.container != ''
        env:
          CMD: |
            cd /workspace
            source container-env.sh
            python3 .github/workflows/build_and_test.py ${{ runner.os }} x86 ${{ matrix.compiler }} ${{ matrix.version }}
        run: docker exec build-container bash -c "$CMD"

  gcc:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - { compiler: gcc,   version: "4.8", os: ubuntu-24.04, container: ubuntu:18.04 }
          - { compiler: gcc,   version: "5",   os: ubuntu-24.04, container: ubuntu:18.04 }
          - { compiler: gcc,   version: "6",   os: ubuntu-24.04, container: ubuntu:18.04 }
          - { compiler: gcc,   version: "7",   os: ubuntu-24.04, container: ubuntu:18.04 }
          - { compiler: gcc,   version: "8",   os: ubuntu-24.04, container: ubuntu:18.04 }
          - { compiler: gcc,   version: "9",   os: ubuntu-22.04                          }
          - { compiler: gcc,   version: "10",  os: ubuntu-24.04                          }
          - { compiler: gcc,   version: "11",  os: ubuntu-24.04                          }
          - { compiler: gcc,   version: "12",  os: ubuntu-24.04                          }
          - { compiler: gcc,   version: "13",  os: ubuntu-24.04                          }
          - { compiler: gcc,   version: "14",  os: ubuntu-24.04                          }
          - { compiler: gcc,   version: "15",  os: ubuntu-24.04, container: ubuntu:26.04 }

    steps:
      - uses: actions/checkout@v5

      # Ref: https://github.com/actions/checkout/issues/1590#issuecomment-2567109195
      - name: Prepare container (containerized)
        if: matrix.container != ''
        run: |
          docker pull ${{ matrix.container }}
          docker run --name build-container -d -v ${{ github.workspace }}:/workspace ${{ matrix.container }} tail -f /dev/null

          cat <<'EOF' > container-env.sh
          export CTEST_OUTPUT_ON_FAILURE="${{ env.CTEST_OUTPUT_ON_FAILURE }}"
          export CTEST_PARALLEL_LEVEL="${{ env.CTEST_PARALLEL_LEVEL }}"
          export CMAKE_GENERATOR="${{ env.CMAKE_GENERATOR }}"
          export ASAN_OPTIONS="${{ env.ASAN_OPTIONS }}"
          export TSAN_OPTIONS="${{ env.TSAN_OPTIONS }}"
          EOF

      - name: Install
        if: matrix.container == ''
        run: |
          # Required for libc6-dbg:i386 and g++-multilib packages which are
          # needed for x86 builds.
          sudo dpkg --add-architecture i386

          sudo apt-get update
          sudo apt-get install -y cmake ninja-build valgrind libc6-dbg:i386
          sudo apt-get install -y g++-${{ matrix.version }} g++-${{ matrix.version }}-multilib

      - name: Install (containerized)
        if: runner.os == 'Linux' && matrix.container != ''
        env:
          CMD: |
            dpkg --add-architecture i386

            # Configure Kitware repo for newer version of CMake.
            if [ "${{ matrix.container }}" = "ubuntu:18.04" ]; then
              apt-get update && apt-get install -y wget gpg
              wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | gpg --dearmor - | tee /usr/share/keyrings/kitware-archive-keyring.gpg >/dev/null
              echo 'deb [signed-by=/usr/share/keyrings/kitware-archive-keyring.gpg] https://apt.kitware.com/ubuntu/ bionic main' | tee /etc/apt/sources.list.d/kitware.list >/dev/null
            fi

            apt-get update
            apt-get install -y cmake ninja-build valgrind libc6-dbg:i386 python3
            apt-get install -y g++-${{ matrix.version }} g++-${{ matrix.version }}-multilib
        run: docker exec build-container bash -c "$CMD"

      - name: Build & Test ${{ runner.arch }}
        if: matrix.container == ''
        run: python3 .github/workflows/build_and_test.py ${{ runner.os }} ${{ runner.arch }} ${{ matrix.compiler }} ${{ matrix.version }}

      - name: Build & Test ${{ runner.arch }} (containerized)
        if: matrix.container != ''
        env:
          CMD: |
            cd /workspace
            source container-env.sh
            python3 .github/workflows/build_and_test.py ${{ runner.os }} ${{ runner.arch }} ${{ matrix.compiler }} ${{ matrix.version }}
        run: docker exec build-container bash -c "$CMD"

      - name: Build & Test X86
        if: matrix.container == ''
        run: python3 .github/workflows/build_and_test.py ${{ runner.os }} x86 ${{ matrix.compiler }} ${{ matrix.version }}

      - name: Build & Test X86 (containerized)
        if: matrix.container != ''
        env:
          CMD: |
            cd /workspace
            source container-env.sh
            python3 .github/workflows/build_and_test.py ${{ runner.os }} x86 ${{ matrix.compiler }} ${{ matrix.version }}
        run: docker exec build-container bash -c "$CMD"

  icc:
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: false
      matrix:
        configuration: ["Debug", "Release"]
        compiler: ["icpc", "icx"]

    steps:
      - uses: actions/checkout@v5

      - name: Install
        run: |
          wget -O - https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB 2>/dev/null | gpg --dearmor - | sudo tee /usr/share/keyrings/oneapi-archive-keyring.gpg >/dev/null
          echo "deb [signed-by=/usr/share/keyrings/oneapi-archive-keyring.gpg] https://apt.repos.intel.com/oneapi all main" | sudo tee /etc/apt/sources.list.d/oneapi.list >/dev/null
          sudo apt-get update
          sudo apt-get install -y intel-oneapi-compiler-dpcpp-cpp-and-cpp-classic ninja-build

      - name: Generate
        run: |
          . /opt/intel/oneapi/setvars.sh
          if [ "${{ matrix.compiler }}" = "icpc" ]; then
            cmake -B build -S . -G Ninja -D CMAKE_C_COMPILER=icc -D CMAKE_CXX_COMPILER=icpc -D CMAKE_BUILD_TYPE=${{ matrix.configuration }} -D CMAKE_CXX_FLAGS="-w2 -Wcheck -Werror -diag-disable=10441 -D DOCTEST_CONFIG_NO_CONTRADICTING_INLINE"
          else
            cmake -B build -S . -G Ninja -D CMAKE_C_COMPILER=icx -D CMAKE_CXX_COMPILER=icpx -D CMAKE_BUILD_TYPE=${{ matrix.configuration }} -D CMAKE_CXX_FLAGS="-Werror -fp-model=precise"
          fi

      - name: Build
        run: |
          . /opt/intel/oneapi/setvars.sh
          cmake --build build --config ${{ matrix.configuration }}

      - name: Test
        run: |
          . /opt/intel/oneapi/setvars.sh
          ctest -C ${{ matrix.configuration }} --test-dir build --no-tests=error
