name: MacOS

on:
  push:
    branches: [dev, master]
    paths-ignore:
      - "doc/**"
      - "scripts/**"
      - "LICENSE.txt"
      - "README.md"

  pull_request:
    paths-ignore:
      - "doc/**"
      - "scripts/**"
      - "LICENSE.txt"
      - "README.md"

env:
  CTEST_OUTPUT_ON_FAILURE: ON
  CTEST_PARALLEL_LEVEL: 2

concurrency:
  group: ${{ github.workflow }}|${{ github.ref_name }}|mac
  cancel-in-progress: true

jobs:
  clang:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - { compiler: xcode, os: macos-14, version: "15.0.1" } # Apple Clang 15.0.0
          - { compiler: xcode, os: macos-14, version: "15.4"   } # Apple Clang 15.0.0
          - { compiler: xcode, os: macos-14, version: "16.2"   } # Apple Clang 16.0.0
          - { compiler: xcode, os: macos-15, version: "16.3"   } # Apple Clang 17.0.0

    steps:
      - uses: actions/checkout@v5

      - name: Install
        run: |
          sudo xcode-select --switch /Applications/Xcode_${{ matrix.version }}.app

      - name: Build and Test (${{ runner.arch }})
        run: python3 .github/workflows/build_and_test.py ${{ runner.os }} ${{ runner.arch }} ${{ matrix.compiler }} ${{ matrix.version }}

  gcc:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - { compiler: gcc, os: macos-14, version: "13" }

    steps:
      - uses: actions/checkout@v5

      - name: Install
        run: |
          sudo xcode-select --switch /Applications/Xcode_15.4.app

      - name: Build and Test (${{ runner.arch }})
        run: python3 .github/workflows/build_and_test.py ${{ runner.os }} ${{ runner.arch }} ${{ matrix.compiler }} ${{ matrix.version }}
