name: Pull Request

on:
  pull_request:
    branches: [dev, master]
    types: [opened, edited, synchronize, reopened]

jobs:
  forbid-merge-to-master:
    runs-on: ubuntu-latest
    if: (github.base_ref == 'master') && (github.head_ref != 'dev')

    steps:
      - name: Fail
        run: |
          echo Pull requests should not target 'master'
          echo Refer to CONTRIBUTING.md
          exit 1
