name: Windows

on:
  push:
    branches: [dev, master]
    paths-ignore:
      - "doc/**"
      - "scripts/**"
      - "LICENSE.txt"
      - "README.md"

  pull_request:
    paths-ignore:
      - ".github/ISSUE_TEMPLATE/**"
      - "doc/**"
      - "scripts/**"
      - "LICENSE.txt"
      - "README.md"

concurrency:
  group: ${{ github.workflow }}|${{ github.ref_name }}|windows
  cancel-in-progress: true

jobs:
  mingw-w64:
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        configuration: ["Debug", "Release"]

    env:
      CMAKE_GENERATOR: MinGW Makefiles

    steps:
      - uses: actions/checkout@v5

      - name: Set up MinGW-w64
        uses: egor-tensin/setup-mingw@v2
        with:
          version: 12.2.0

      - name: Generate
        shell: bash
        run: |
          cmake -B build -S . -D CMAKE_BUILD_TYPE=${{ matrix.configuration }}

      - name: Build
        run: cmake --build build

      - name: Test
        run: ctest --test-dir build --no-tests=error

  msvc:
    runs-on: windows-2025

    strategy:
      fail-fast: false
      matrix:
        compiler:   ["cl", "clang", "clang-cl"]
        arch:       [x64, x86]
        build-type: [Release, Debug]
        target:     [test]

        exclude:
          - { compiler: cl,       arch: x86 }
          - { compiler: clang-cl, arch: x86 }

    steps:
      - uses: actions/checkout@v5

      - name: Configure MSVC (x64)
        if:   matrix.arch == 'x64'
        uses: ilammy/msvc-dev-cmd@v1

      - name: Configure MSVC (x86)
        if:   matrix.arch == 'x86'
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x86

      - name: Build & Test
        shell: bash
        run: |
          python3 .github/scripts/cmake.py        \
            --os         ${{ runner.os }}         \
            --arch       ${{ matrix.arch }}       \
            --compiler   ${{ matrix.compiler }}   \
            --build-type ${{ matrix.build-type }} \
            --target     ${{ matrix.target }}

  msvs:
    runs-on:  "windows-2025"

    strategy:
      fail-fast: false
      matrix:
        toolset: ["v142", "v143"]
        architecture: ["Win32", "x64"]
        configuration: ["Debug", "Release"]

    steps:
      - uses: actions/checkout@v5

      - name: Generate
        run:
          cmake -B build -S . -G "Visual Studio 17 2022" \
          -A ${{ matrix.architecture }} -T ${{ matrix.toolset }}

      - name: Build
        run: cmake --build build --config ${{ matrix.configuration }}

      - name: Test
        run: ctest -C ${{ matrix.configuration }} --test-dir build --no-tests=error
